apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: django-metrics
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: backend
  namespaceSelector:
    matchNames:
      - rikili001
  endpoints:
  - port: http
    path: /metrics
    interval: 30s