# Generated by Django 4.2.8 on 2026-04-08 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organization_description_organization_email_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('estimated_delivery_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor_type', models.CharField(choices=[('private', 'Private Donor'), ('government', 'Government')], default='private', max_length=20)),
                ('donor_name', models.CharField(blank=True, max_length=200)),
                ('donor_contact', models.CharField(blank=True, max_length=50)),
                ('donor_organization', models.CharField(blank=True, max_length=200)),
                ('donor_address', models.TextField(blank=True)),
                ('donor_email', models.EmailField(blank=True, max_length=254)),
                ('donor_phone', models.CharField(blank=True, max_length=20)),
                ('government_department', models.CharField(blank=True, max_length=200)),
                ('government_program', models.CharField(blank=True, max_length=200)),
                ('government_officer_name', models.CharField(blank=True, max_length=200)),
                ('government_officer_designation', models.CharField(blank=True, max_length=100)),
                ('government_officer_contact', models.CharField(blank=True, max_length=20)),
                ('donation_letter_file', models.FileField(blank=True, null=True, upload_to='donation_letters/')),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL)),
                ('need_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='core.needitem')),
            ],
        ),
    ]
