# Generated by Django 4.2.8 on 2026-04-08 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='admin_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_org', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_organization_name'),
        ),
    ]
