# Generated by Django 6.0.3 on 2026-04-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_donation_id_alter_needitem_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donor_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_contact',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_organization',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_type',
            field=models.CharField(blank=True, choices=[('private', 'Private Citizen / NGO / Corporate'), ('government', 'Government Sponsor')], default='private', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='government_department',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='donation',
            name='government_officer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='donation',
            name='government_officer_contact',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='donation',
            name='government_program',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='donation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='needitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
