# Generated by Django 6.0.3 on 2026-04-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_donation_donor_address_donation_donor_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='government_officer',
            new_name='government_officer_name',
        ),
        migrations.AddField(
            model_name='donation',
            name='government_officer_designation',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
