# Generated by Django 6.0.3 on 2026-04-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_government_officer_donation_government_officer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donation_letter_file',
            field=models.FileField(blank=True, help_text='Uploaded signed donation confirmation letter (PDF)', null=True, upload_to='donation_letters/'),
        ),
    ]
