# Generated by Django 6.0.3 on 2026-04-11 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_donation_id_alter_needitem_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approval_decided_at',
            field=models.DateTimeField(blank=True, help_text='When the approval/rejection decision was made', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='approval_decided_by',
            field=models.ForeignKey(blank=True, help_text='The admin who approved/rejected this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='approval_requested_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the org admin request was submitted', null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='needitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
