# Generated by Django 6.0.3 on 2026-04-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_approval_decided_at_user_approval_decided_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='requested_organization_type',
            field=models.CharField(blank=True, help_text='Organization type submitted during org admin registration (HOSPITAL, CLINIC, etc.)', max_length=50),
        ),
    ]
