# Generated by Django 6.0.3 on 2026-04-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_requested_organization_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='requested_organization_name',
            field=models.CharField(blank=True, help_text='Organization name submitted during org admin registration', max_length=255),
        ),
    ]
