# Generated by Django 5.1.4 on 2026-04-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_requested_organization_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='needitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='requested_organization_type',
            field=models.CharField(blank=True, choices=[('HOSPITAL', 'Hospital'), ('CLINIC', 'Clinic'), ('SCHOOL', 'School'), ('NGO', 'NGO'), ('CHARITY', 'Charity'), ('GOVERNMENT', 'Government'), ('OTHER', 'Other')], help_text='Organization type submitted during org admin registration', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'System Admin'), ('ORG_ADMIN', 'Org Admin'), ('DONOR', 'Donor')], default='DONOR', max_length=20),
        ),
    ]
